# Copyright 2026 Astro Survey Atlas contributors.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.

{{- if and .Values.mocDiscovery.enabled .Values.mocDiscovery.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.mocDiscovery.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "atlas-warehouse-operator.labels" . | nindent 4 }}
{{- end }}
