# Copyright 2026 Astro Survey Atlas contributors.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- range .Values.watchNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "atlas-warehouse-operator.fullname" $ }}
  namespace: {{ . }}
  labels:
    {{- include "atlas-warehouse-operator.labels" $ | nindent 4 }}
rules:
  - apiGroups: ["atlas.zhejianglab.org"]
    resources: ["scanrequests"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["atlas.zhejianglab.org"]
    resources: ["scanrequests/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "atlas-warehouse-operator.fullname" $ }}
  namespace: {{ . }}
  labels:
    {{- include "atlas-warehouse-operator.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "atlas-warehouse-operator.fullname" $ }}
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.operator.serviceAccount.name }}
    namespace: {{ $.Values.operator.namespace }}
---
{{- if $.Values.mocDiscovery.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "atlas-warehouse-operator.fullname" $ }}-moc-discovery
  namespace: {{ . }}
  labels:
    {{- include "atlas-warehouse-operator.labels" $ | nindent 4 }}
rules:
  - apiGroups: ["atlas.zhejianglab.org"]
    resources: ["mocdiscoveryrequests"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["atlas.zhejianglab.org"]
    resources: ["mocdiscoveryrequests/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "atlas-warehouse-operator.fullname" $ }}-moc-discovery
  namespace: {{ . }}
  labels:
    {{- include "atlas-warehouse-operator.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "atlas-warehouse-operator.fullname" $ }}-moc-discovery
subjects:
  - kind: ServiceAccount
    name: {{ $.Values.mocDiscovery.serviceAccount.name }}
    namespace: {{ $.Values.operator.namespace }}
{{- end }}
---
{{- end }}
