apiVersion: apps/v1
kind: Deployment
metadata:
  name: astro-atlas-operator
  namespace: atlas-system
  labels:
    app.kubernetes.io/name: astro-atlas-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: astro-atlas-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: astro-atlas-operator
    spec:
      serviceAccountName: astro-atlas-operator
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: tmp
          emptyDir: {}
      containers:
        - name: operator
          image: crpi-wixjy6gci86ms14e.cn-hongkong.personal.cr.aliyuncs.com/ay-dev/astro-atlas-operator:0.2.0-20260825-fix2
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              value: atlas-warehouse
            - name: SCANNER_IMAGE
              value: crpi-wixjy6gci86ms14e.cn-hongkong.personal.cr.aliyuncs.com/ay-dev/astro-atlas-scanner:0.2.0-20260825-fix3
            - name: RECONCILE_INTERVAL_SECONDS
              value: "10"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
