apiVersion: v1
kind: ServiceAccount
metadata:
  name: astro-atlas-operator
  namespace: atlas-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: astro-atlas-operator
rules:
  - apiGroups:
      - atlas.zhejianglab.org
    resources:
      - scanrequests
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - atlas.zhejianglab.org
    resources:
      - scanrequests/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - atlas.zhejianglab.org
    resources:
      - mocdiscoveryrequests
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - atlas.zhejianglab.org
    resources:
      - mocdiscoveryrequests/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: astro-atlas-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: astro-atlas-operator
subjects:
  - kind: ServiceAccount
    name: astro-atlas-operator
    namespace: atlas-system
